### ISSUE TITLE
Question about duration and timing

### ISSUE THREAD

**Issue by heckt007** [maxwellito/vivus#165] opened 2017-07-26 07:36 UTC
Hi,

vivus is a great tool! I have an issue with duration/frames and timing. I'd like to use vivus for a research project, where I want to animate very special SVG files (pretty complex paths). The animation itself works perfectly, but I have issues setting the right timing/duration. 

The whole animation in vivus is based on frames. I need a way to set this to milliseconds. E.g. I have an SVG to animate that needs to run e.g. 4307 milliseconds. Is there a way to convert frames to milliseconds, or make vivus even work with milliseconds directly?

Thanks a lot
Thomas

**Comment by maxwellito** [comment] 2017-07-26 10:35
Hi Thomas,

Im afraid Vivus animation is based on frames so there's no way to garantee
the timing. However, if you just want to display the animation maybe Vivus
instant might be the solution for you. It will create a duplicate of your
SVG with CSS animation included to obtain the same result as Vivus but CSS
powered. In this case you will be able to set the timing.

https://maxwellito.github.io/vivus-instant/

I hope this will help :-S

Thanks

**Closed** 2017-08-05 18:20 UTC
