### ISSUE TITLE
Path animation doesn't work on Chrome for dynamic loaded SVGs

### ISSUE THREAD

**Issue by pixedelic** [maxwellito/vivus#198] opened 2018-06-11 15:02 UTC
Hello, on Chrome 67 for Max OSX if I include an SVG via the option "file", simple paths can't be animated anymore. All the other elements seem to work fine: lines, circles etc. But paths get stuck.

Here is an example: http://pixedelic.com/test/chrome-vivus/ The first row displays an SVG dynamically loaded from the server, the second row displays an SVG put into the document as code. As you can see the parts on the first icon made by paths get stuck.

Any advice? TYIA

**Comment by maxwellito** [comment] 2018-06-11 18:25
Hi @pixedelic 
Thanks for reporting, that look major. I think that's what @mittererr what talking about in the [previous issue](https://github.com/maxwellito/vivus/issues/196#issuecomment-396129297). I'm having a look right now. Thanks for setting up the demo page.

**Comment by maxwellito** [comment] 2018-06-11 19:24
Ok, strange things are happening. I dunno why but Chrome doesn't update correctly elements contained in an `Object` tag. So, I did an update I wanted to do for a while but it can have some negative effects, it's to get rid of the object tag. In this version I load the SVG via XMLHttpRequest and put it in the DOM. It looks like it works like a charm. But I have the feeling that some other SVGs won't like it.

http://maxwellito.github.io/drafts/vivus-198/index.html

**Comment by pixedelic** [comment] 2018-06-12 06:41
Thank you @maxwellito for the incredible prompt reaction. I'm testing your changes at this very moment, and they actually seem to work like a charm. What kind of SVGs do you thing won't like this update? I could do some "stress tests" maybe.

Thank you again, great piece of work BTW

**Comment by maxwellito** [comment] 2018-06-12 08:05
Hehe thanks :)

I'm thinking of SVGs with a fixed size or with embedded styling. Ill have
to update the doc to explain the new behavior. But I guess Im too anxious
to ship breaking changes.
If all works well Ill ship a new version tonight.

**Comment by pixedelic** [comment] 2018-06-12 15:45
Well... maybe this is one of that things to report here https://bugs.chromium.org/p/chromium/issues/list ?

**Comment by maxwellito** [comment] 2018-06-12 22:42
It's been 2 hours I try to provide a basic example for Chromium bug report, without Vivus, and everything works. Step after step I add stuff to mimic Vivus behavior and everything works. I'm going mad, but I'll find the problem.

The truth is out there.

**Comment by maxwellito** [comment] 2018-06-13 07:41
I sorted it out! The problem was when the SVG is extracted from an Object tag. Chrome doesn't manipulate it correctly. I created a [demo](http://maxwellito.github.io/drafts/vivus-198/bug.html) to reproduce the bug and created a ticket on Chromium.

So in the the end I forgot that the SVG wasn't sandboxed but part of the main DOM. The behavior is actually the same as with my fix. So I pushed to v0.4.4, it's live :)

**Comment by pixedelic** [comment] 2018-06-13 09:20
Thank you so much!

**Comment by maxwellito** [comment] 2018-06-13 21:20
Thank you guys!

But special thanks @pixedelic and @mittererr for reporting the bug!
The Chromium team seems to be on it. I was surprised by their reactivity. Here is the [bug ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=852190) if you're curious.

So far, I think I can close this ticket. I'll reopen it if a problem come up.

**Closed by maxwellito** 2018-06-13 21:20 UTC
